### ISSUE TITLE
Integerating storybook for react components

### ISSUE THREAD

**Issue by Sanskar95** [KTH/kth-style-react-components#54]
Storybook is a tool for UI development. It makes development faster and easier by isolating components. This allows you to work on one component at a time. You can develop entire UIs without needing to start up a complex dev stack, force certain data into your database, or navigate around your application.

https://storybook.js.org/docs/react/get-started/introduction

**Comment by hoyce** [comment]
Hi Sanskar!

Sorry for the very late answer and thanks for the tip!
